# -*- coding: utf-8 -*-
"""MODULE1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ohkXWIS2Nr2SvipBL5plJchKG_geOLhO

Write a program to visualize the total profit of all months using line plot.
"""

import matplotlib.pyplot as plt
import pandas as pd

df=pd.read_csv("Sales.csv")
df.head()

X=df.month_name
Y=df.total_profit
plt.plot(X,Y)

"""Write a program to visualize total profit of all months and show line plot with the following Style properties."""

X=df.month_name
Y=df.total_profit
plt.plot(X,Y,linestyle='dotted',color='blue',marker="o",markerfacecolor="yellow",linewidth=5)
plt.legend(["blue"], loc='upper right')
plt.xlabel("Month Number")
plt.ylabel("Item Sold units number")
plt.show()

"""Using pie chart visualize total unit’s sale data for last year for each product."""

plt.pie(df.total_units,labels=X)

"""Write a python Matplotlib program to plot y=x^2 (parabola) and add text "Parabola $Y = x^2$" in the plot."""

import numpy as np
x  = np.linspace(-50,50,100)
y = x**2
plt.plot(x,y)
plt.title("Parabola $Y = x^2$")
plt.show()

"""Write a python Matplotlib program to visualize a bar plot for given values"""

X=[1,2,3,4,5,6]
Y=[16,23,24,25,90,32]
plt.bar(X,Y)
plt.show()